version: "3.5"

networks:
  bazel-remote-executor_remote-server:
    external: true

services:
  frontend:
    build: .
    ports:
      - "5432:5432"
    container_name: frontend
    networks:
       bazel-remote-executor_remote-server: